#!/usr/bin/env bash

source files-to-encrypt

for file in ${files_to_encrypt[@]}; do
  if ! grep -q '$ANSIBLE_VAULT' "$file"; then
    echo "$file is not encrypted, run the ENCRYPT command !"
    exit 1
  fi
done



