#!/usr/bin/env bash

source files-to-encrypt

files_added=$(git diff --name-only --cached --diff-filter=AM)

for x in ${files_to_encrypt[@]}; do
  for y in ${files_added[@]}; do
    if [ "$x" = "$y" ]; then
      echo "Change were made on sensitive file $x, restoring... !"
      git restore --staged $x
      git restore $x
    fi
  done
done
