#!/usr/bin/env bash

source files-to-encrypt

for file in ${files_to_encrypt[@]}; do
  if ! grep -q '$ANSIBLE_VAULT' "$file"; then
    echo "Encrypting $file"
    ansible-vault encrypt $file
    echo -en "\n"
  else
    echo "$file is already encrypted !"
  fi
done

