#!/usr/bin/env bash

# git config core.hooksPath ./git-hooks

packages=(
  "git"
  "ansible"
  "docker"
)

if [[ "$OSTYPE" == "darwin"* ]]; then # Mac OSX 
  echo "Running installation on Mac OSX"
  # Install Brew
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

  for p in ${packages[@]}; do
    echo "Installing $p..."
    brew install $p
    echo " "
  done

fi

if [[ "$OSTYPE" == "linux-gnu"* ]]; then # Linux
  echo "Running installation on Linux"
  # TODO: Install last verion of packages

  for p in ${packages[@]}; do
    echo "Installing $p..."
    apt-get install $p -y
    echo " "
  done
fi


# Enale git pre commit hooks !
# https://dev.to/krzysztofkaczy9/do-you-really-need-husky-247b
git config core.hooksPath ./git-hooks

