---
- hosts: localhost
  connection: local
  vars:
    ssh:
      source_key: "./.ssh/id_ed25519"
      dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    github:
      user: alexandre-dos-reis
    fish:
      bin: /usr/bin/fish
      plugins:
        - jorgebucaran/autopair.fish
        - ilancosman/tide@v5
        - jhillyerd/plugin-git
        - jorgebucaran/nvm.fish
        - catppuccin/fish
    packages:
      - git
      - unzip
      - openssh
      - telnet
      - wget
      - curl
      - fzf
      - bat
      - htop
      - gnupg
      - exa
      - jq
      - tmux
    neovim:
      deps: ["ripgrep", "fd"]
    terminals: ["kitty", "alacritty"]
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/chezmoi.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/terminals.yml
    # - import_tasks: tasks/vscode.yml
    - import_tasks: tasks/nodejs.yml
    - import_tasks: tasks/bun.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/golang.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/docker.yml
