# For Ubuntu
- name: Add fish repository on Ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  apt_repository:
    repo: ppa:fish-shell/release-3
    state: present

- name: Install Fish on Ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  apt:
    name: fish

# For Arch
- name: Install Fish on Arch
  when: ansible_distribution == "Archlinux"
  become: true
  pacman:
    name: fish

# For MacOSX
- name: Install Fish on MacOSX
  when: ansible_distribution == "MacOSX"
  become: true
  homebrew:
    name: fish

# Fisher, Fish plugin manager
- name: Install Fisher | Fish plugin manager
  shell:
    executable: "{{ fish.bin }}"
    cmd: curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher

- name: Install Fisher plugins
  loop: "{{ fish.plugins }}"
  shell:
    executable: "{{ fish.bin }}"
    cmd: "fisher install {{ item }}"

- name: Install MacOSX Fisher plugins
  when: ansible_distribution == "MacOSX"
  shell:
    executable: "{{ fish.bin }}"
    cmd: fisher install nifoc/ssh-agent-macos.fish

- name: Install Linux Fisher plugins
  when: ansible_distribution != "MacOSX"
  shell:
    executable: "{{ fish.bin }}"
    cmd: fisher install danhper/fish-ssh-agent

- name: Make fish the default shell
  become: true
  user:
    name: alex
    shell: "{{ fish.bin }}"
