- name: Ensure .ssh directory exists.
  file:
    dest: "{{ ssh.dest_key | dirname }}"
    mode: 0700
    state: directory

- name: Install ssh key
  copy:
    src: "{{ ssh.source_key }}"
    dest: "{{ ssh.dest_key }}"
    mode: 0600

- name: Install public ssh key
  copy:
    src: "{{ ssh.source_key }}.pub"
    dest: "{{ ssh.dest_key }}.pub"
    mode: 0644
