- name: Install editors on Arch
  when: ansible_distribution == "Archlinux"
  become: true
  pacman:
    name: "code"

- name: Install editors on MacOSX
  when: ansible_distribution == "MacOSX"
  become: true
  homebrew_cask:
    name: "visual-studio-code"

# https://code.visualstudio.com/docs/setup/linux
- name: Install editors on Ubuntu
  when: ansible_distribution == "Ubuntu"
  become: true
  apt:
    name: "code"
